In [1]:
import numpy as np
a1=np.array([[2,4],[1,4]])
a2=np.array([[1,3],[4,6]])
print(a1)


[[2 4]
 [1 4]]


In [2]:
print(a2)

[[1 3]
 [4 6]]


In [4]:
print("transpose of matrix")
x=a1.transpose()
print(x)

transpose of matrix
[[2 1]
 [4 4]]


In [5]:
y=a2.transpose()
print(y)

[[1 4]
 [3 6]]


In [6]:
print("add two matrix")
x=np.add(a1,a2)
print(x)

add two matrix
[[ 3  7]
 [ 5 10]]
